name: Python package

on:
#  push:
  release:
    types:
      - published

jobs:
  build-wheels:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel cibuildwheel
    - name: Build
      run: |
        cd Bindings/Python
        python copy-cpp-files.py
        python -m cibuildwheel
      env:
        CIBW_ARCHS: auto64
        # C++17 support started in MacOS 10.13, full support in 10.14+
        MACOSX_DEPLOYMENT_TARGET: 10.14
    - uses: actions/upload-artifact@v2
      with:
        path: Bindings/Python/wheelhouse/*.whl




