name: Python package

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Doxa_wheel'
        required: true
        default: 'Doxa_wheel'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-wheels:

    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.11]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel cibuildwheel
    - name: Build
      run: |
        cd Bindings/Python
        python copy-cpp-files.py
        python -m cibuildwheel
      env:
        CIBW_ARCHS: auto64
        # C++17 support started in MacOS 10.13, full support in 10.14+

    - uses: actions/upload-artifact@v4
      with:
        path: Bindings/Python/wheelhouse/




